services:
  front:
    build:
      context: .
    container_name: matsu-front
    ports:
      - 5173:5173
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_BFF_BASE_URL=http://localhost:18082
