services:
  front:
    build:
      context: .
    container_name: matsu-front
    ports:
      - 5173:5173
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
    environment:
      - VITE_BFF_BASE_URL=http://localhost:18082
